name: Linux

on: [push, pull_request]

jobs:
  build:
    name: Linux ${{ matrix.type }}

    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        auto-update-conda: true

    - name: Setup
      shell: bash -l {0}
      run: |
          source ./ci/linux/setup.sh

    - name: CMake
      shell: bash -l {0}
      run: |
          source ../ci/linux/cmake.sh
      working-directory: ./build

    - name: Compile
      shell: bash -l {0}
      run: |
          source ../ci/linux/compile.sh
      working-directory: ./build

    - name: Test
      shell: bash -l {0}
      run: |
          source ../ci/linux/test.sh
      working-directory: ./build


